version: '3.3'
services:
    database:
        build: ./database
        ports:
            - '1433:1433'
        container_name: car_parking
    database_tests:
        build: ./database
        ports:
            - '1434:1433'
        container_name: car_parking_tests